Vagrant.configure("2") do |config|

    config.vm.define "pdvmthree" do |pdvmthree|

        pdvmthree.vm.hostname = "pdvmthree"
        pdvmthree.vm.box = "ubuntu/focal64"
        pdvmthree.vm.network "private_network", ip: "192.168.33.10"
        pdvmthree.vm.network "forwarded_port", guest: 80, host: 8888


        pdvmthree.vm.provider "virtualbox" do |vb|
            vb.name = "pdvmthree"
            vb.gui = false
            vb.memory = "1024"
        end

        config.vm.provision "shell", run: "always", path: "script.sh"
    end
end
