Vagrant.configure("2") do |config|

    config.vm.define "pdvmfour" do |pdvmfour|

        pdvmfour.vm.hostname = "pdvmfour"
        pdvmfour.vm.box = "ubuntu/focal64"
        pdvmfour.vm.network "private_network", ip: "192.168.33.10"
        pdvmfour.vm.network "forwarded_port", guest: 80, host: 8889


        pdvmfour.vm.provider "virtualbox" do |vb|
            vb.name = "pdvmfour"
            vb.gui = false
            vb.memory = "1024"
        end

        config.vm.provision "shell", run: "always", path: "script.sh"
    end
end