ENV["VAGRANT_EXPERIMENTAL"] = "disks"

Vagrant.configure("2") do |config|

    config.vm.define "pdvmsix" do |pdvmsix|

        pdvmsix.vm.hostname = "pdvmsix"
        pdvmsix.vm.box = "ubuntu/focal64"
        pdvmsix.vm.network "private_network", ip: "192.168.33.10"
        pdvmsix.vm.network "forwarded_port", guest: 80, host: 8888


        config.vm.disk :disk, size: "300MB", name: "disk_1"
        config.vm.disk :disk, size: "300MB", name: "disk_2"
        config.vm.disk :disk, size: "300MB", name: "disk_3"
        config.vm.disk :disk, size: "300MB", name: "disk_4"

        pdvmsix.vm.provider "virtualbox" do |vb|
            vb.name = "pdvmsix"
            vb.gui = false
            vb.memory = "1024"
        end

        config.vm.provision "shell", run: "always", path: "script.sh"
    end
end